name: Bahamut 自動簽到

on:
  schedule:
    - cron: '5 20 * * *'
  workflow_dispatch:

jobs:
  signin:
    runs-on: ubuntu-latest

    steps:
      - name: 巴哈姆特自動簽到
        uses: JacobLinCool/bahamut-automation@v0.6.9
        with:
          config: |
            bahamut:
              username: "${{ secrets.BAHAMUT_USERNAME }}"
              password: "${{ secrets.BAHAMUT_PASSWORD }}"
            modules:
              - signin
